[package]
name = "yolir"
version = "0.0.0"
authors = ["Matrixmage <osmithsi@sfu.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
